// <auto-generated />
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "admin@example.com",
                            FirstName = "Karim",
                            LastName = "Khairy",
                            Password = "AQAAAAEAACcQAAAAEIHwIQs4yBoSwjyOcKLVBOqOLEG3SorntvkC+eaKsu8plBmtuhpCDbRjV9UhleyVDQ==",
                            Phone = "01112202144",
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2L,
                            Email = "admin2@example.com",
                            FirstName = "Mohamed",
                            LastName = "Gazzar",
                            Password = "AQAAAAEAACcQAAAAED9EMoRBp+l+V74kHwsKOpD6I7C+L/yiNdZJarH0f56O03AD1vAASn7UJ9rF26LCLA==",
                            UserName = "admin2"
                        },
                        new
                        {
                            Id = 3L,
                            Email = "karim.khairy@example.com",
                            FirstName = "Karim2",
                            LastName = "Khairy2",
                            Password = "AQAAAAEAACcQAAAAEFOLTXpn6deLP4Y6e9j9UlcqYmq1tb6p/atrUX0OhEwKdRicq64FROAnU8rU34QHmg==",
                            UserName = "karim.khairy"
                        },
                        new
                        {
                            Id = 4L,
                            Email = "mohmaed.diaa@example.com",
                            FirstName = "Mohamed",
                            LastName = "Diaa",
                            Password = "AQAAAAEAACcQAAAAEMTwUp35fWj2FijPG8xEciLOS3mt0/ii0XPLuB7WeocDgHmYmwJJsvxI4ffdV9+knA==",
                            UserName = "mohmaed.diaa"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
